theme: minima

title: Vysakh KS
author: Vysakh KS
email: vyshuks@gmail.com
url: https://vyshuks.github.io/


description: >
  My first blog. Probably no one else will ever read it, but oh well.
# Minima variables
github_username:   vyshuks
rss: rss
