theme: minima

title: Vysakh KS
author: Vysakh KS
email: vyshuks@gmail.com
url: https://vyshuks.github.io/


description: >
  Hi there! I’m a Software developer from kochi, Kerala.
# Minima variables
github_username:   vyshuks
linkedin_username: vysakh-ks
rss: rss
