theme: minima

title: Vysakh KS
author: Vysakh KS
url: https://vyshuks.github.io/


description: >
  
# Minima variables
#twitter_username:  
github_username:   vyshuks
linkedin_username: vysakh-ks
rss: rss

show_excerpts: false

# Used by simple links page
social-links:
  LinkedIn:      https://www.linkedin.com/in/vysakh-ks/
  GitHub:        https://github.com/vyshuks
  Website:       https://vyshuks.github.io/
  Email:         mailto:vyshuks@gmail.com

# plugin: jekyll-seo-tag

social:
  name: Vysakh KS
  links:
    - https://www.linkedin.com/in/vysakh-ks/
    - https://github.com/vyshuks

# plugin: jekyll-titles-from-headings
titles_from_headings:
  strip_title: true

collections:
  personal: # collection for personal blog posts
    output: true

header_pages:
  - archive.html

plugins:
  - jekyll-feed
  - jekyll-sitemap

google_analytics:
#   - UA-185058308-1 # Old GA Universal Analytics property
  - G-8HRT4T6EV5 # New GA4 property

gravatar_hash: 2136e716a089f4a3794f4007328c7bfb
code_block_max_height: 500px

home_post_limit: 5

# The github repo that is to be used for looking up comments
comments_repo: vyshuks/vyshuks.github.io

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags:
        - Technology # Add a default tag to all posts

# Disable highlighting to use highlightJS instead
# highlighter: none # Not supported by GitHub Pages
kramdown:
  syntax_highlighter_opts:
    disable: true
